
export const FETCH_CLUB_LIST = 'cms/user/FETCH_CLUB_LIST'
export const FETCH_CLUB_LIST_SUCCESS = 'cms/user/FETCH_CLUB_LIST_SUCCESS'
export const FETCH_CLUB_LIST_ERROR = 'cms/user/FETCH_CLUB_LIST_ERROR'